
show-level-as-prefix: true
#Set to false to disable the [1] (level number) prefix before
#players' names. Leave true to keep it.
send-message-on-levelup: true
#Set to false to disable the message sent to a player when they level up
levelup-message: '&aYou leveled up! New server level: %level%'
max-level: 100
#Players will not be able to go above this level. Set to 0 to disable.
#Maximum level is REQUIRED for several plugins this plugin has support for!
use-milestones: true
#Set to false to disable the milestones feature.
#(Milestones give players rewards for leveling to a certain level)
prefix-border-color: '7'
prefix-number-color: 'f'
#Use color codes WITHOUT the & to determine the colors
exp-per-level: 8.0
#The amount of exp required to go from level 1 to level 2.
#Used as a baseline to determine exp of further levels.
exp-multiplier: 1.1
#If everything is set to default, and exp-per-level is 10
#and exp-multiplier is 1.1, this will take that 10 exp and multiply it
#1.1 for each level. level 3 requires 11 exp instead of 10 (10 X 1.1).
#Level 4 requires 22 exp instead of 11, and so on.
exp-on-chat: 0.2
exp-on-mobkill: 0.4
exp-on-playerkill: 0.6
exp-on-blockbreak: 0.01
exp-on-blockplace: 0.01
#exp given for an event. SET TO -1.0 TO DISABLE!
#If disabled they will also disabled them for extra level systems!
#Set to 0 to use for other systems only

extra-level-systems: false
#The above allows you to have multiple level systems apart from the default system.
#This would allow you to, for example, have 2 separate level systems for mining and combat.

#Request new events, features, or other in the discord: https://discord.gg/xBS7jk6Wtg

config-version: "1.2"
#Do not touch!