name: ServerLevels
main: net.cozycosmos.serverlevels.Main
author: Miden
version: 1.3.1
api-version: 1.13

commands:
  serverlevels:
    description: Core command for the Server Levels Plugin
    permission: serverlevels.command
    usage: /serverlevels
    aliases: [sl]
permissions:
  serverlevels.command:
    description: Allows use of core command for ServerLevels
    default: op
  serverlevels.SetExp:
    description: Gives access to the /sl set exp command
    default: op
  serverlevels.SetLevel:
    description: Gives access to the /sl set level command
    default: op
  serverlevels.reload:
    description: Gives access to the /sl reload command
    default: op
  serverlevels.SetMultiplier:
    description: Gives access to the /sl set multiplier command
    default: op
  serverlevels.SetPlayerMultiplier:
    description: Gives access to the /sl set playermultiplier command
    default: op
